### ISSUE TITLE
Installation fails due to archived CRAN dependency (grr)

### ISSUE THREAD

**Issue by sebrauschert** [cole-trapnell-lab/monocle3#772]
**Describe the bug**

Installation of monocle3 fails because the `grr` package dependency was archived and removed from CRAN on 2025-12-10. This affects all new installations.

CRAN notice: https://CRAN.R-project.org/package=grr
> Package 'grr' was removed from the CRAN repository.
> Archived on 2025-12-10 as issues were not corrected in time.

**To Reproduce**

```r
renv::install('cole-trapnell-lab/monocle3')
```

Or equivalently:
```r
devtools::install_github('cole-trapnell-lab/monocle3')
```

**traceback()**

```
23: renv::install('cole-trapnell-lab/monocle3')
22: renv_retrieve_impl(packages)
21: handler(package, renv_retrieve_impl_one(package))
20: renv_retrieve_impl_one(package)
19: renv_retrieve_github(record)
18: renv_retrieve_package(record, url, path)
17: renv_retrieve_successful(record, path)
16: (function() {
        if (nzchar(desc[["biocViews"]] %||% "")) {
            repos <- renv_bioconductor_repos()
            renv_scope_options(repos = repos)
        }
        renv_retrieve_successful_recurse(strongdeps)
    })()
15: renv_retrieve_successful_recurse(strongdeps)
14: renv_retrieve_successful_recurse_impl(remote)
13: dynamic(key = list(remote = remote), value = renv_retrieve_successful_recurse_impl_one(remote), 
        force = force)
12: the$dynamic_objects[[id]] %||% {
        dlog("dynamic", "memoizing dynamic value for '%s'", id)
        value
    }
11: renv_retrieve_successful_recurse_impl_one(remote)
10: renv_retrieve_impl_one(remote)
 9: renv_retrieve_repos(record)
 8: renv_retrieve_repos_impl(record)
 7: renv_retrieve_package(record, url, path)
 6: stop(status)
 5: <condition-handler>(...)
 4: <condition-handler>(...)
 3: invoke_option_error_handler()
 2: withCallingHandlers(...)
 1: error_handler()
```

**Expected behavior**

monocle3 should install successfully with all dependencies resolved.

**sessionInfo()**

independent of session

**Additional context**

- **OS:** macOS (Apple Silicon)
- **R version:** 4.5

**Current workaround:**

```r
install.packages("https://cran.r-project.org/src/contrib/Archive/grr/grr_0.9.5.tar.gz", 
                 repos = NULL, 
                 type = "source")
renv::install('cole-trapnell-lab/monocle3')
```

**Suggested fixes:**
1. Replace `grr` with an alternative package providing similar functionality
2. Vendor the required functions from `grr` directly into monocle3
3. Add installation instructions noting this issue until a fix is released

**Comment by Frank1213817** [comment]
Extremely helpful workaround! Appreciate it!
Looking forward to seeing improvement done by the dev team

**Comment by mragsac** [comment]
Extremely helpful! Thank you for the workaround!

**Comment by dr-gu** [comment]
Extremely helpful ！THANK YOU！

**Comment by saikatds-bd** [comment]
Thank you for the workaround. It did work well in R version 4.5. But unfortunately the grr package (even with the workaround) no longer supports R version 4.6.

**Comment by hsuknowledge** [comment]
Regarding the grr package, STRING_PTR (used for mutating the string object) was not a legal R API call and was removed in R 4.6.0. Search-and-replace as hinted below does not help.

```cpp
using C++ compiler: ‘g++ (Debian 14.2.0-19) 14.2.0’
g++ -std=gnu++20 -I"/opt/R/R-4.6.0/lib/R/include" -DNDEBUG  -g -O2 -march=native -pipe -Wno-ignored-attributes  -I/usr/local/include    -fpic  -g -O2 -march=native -pipe -Wno-ignored-attributes  -c grr.cpp -o grr.o
grr.cpp: In function ‘SEXPREC* sortcpp(SEXP)’:
grr.cpp:43:17: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
   43 |       std::sort(STRING_PTR(x), STRING_PTR(x) + LENGTH(x), cmp_char);
      |                 ^~~~~~~~~~
      |                 STRING_PTR_RO
grr.cpp: In function ‘void internalOrder(int*, SEXP)’:
grr.cpp:116:20: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
  116 |     SEXP* start = &STRING_PTR(x)[0];
      |                    ^~~~~~~~~~
      |                    STRING_PTR_RO
grr.cpp: In function ‘SEXPREC* matches(SEXP, SEXP)’:
grr.cpp:283:21: error: ‘STRING_PTR’ was not declared in this scope; did you mean ‘STRING_PTR_RO’?
  283 |     SEXP* astart = &STRING_PTR(a)[0];
      |                     ^~~~~~~~~~
      |                     STRING_PTR_RO
make: *** [/opt/R/R-4.6.0/lib/R/etc/Makeconf:199: grr.o] Error 1
ERROR: compilation failed for package ‘grr’
```

**Comment by hsuknowledge** [comment]
grr is an outdated package and its C++ codes are nothing more than redundant copies of R builtin `sort`, `order`, `match` functions.

Actually, the entire grr dependency can be **removed**. It's easy to replace the single call to grr::extract() found in the entire monocle3 project. This function does not involve any C call.

https://github.com/cole-trapnell-lab/monocle3/blob/4f4239a0afb0dd1941a0359ba6bec95eb0ccf628/R/cluster_genes.R#L249-L250

<details>
<summary>grr::extract source code</summary>

```R
extract<-function(x,i=NULL,j=NULL)
{
  if(is.null(dim(x)))
  {
     x<-x[i]
    return(x)
  }
  else
    if(!is.null(j))
      x<-x[,j]
  if(!is.null(i))
  {
  if(is.data.frame(x))
    x<-as.data.frame(lapply(x,function (a) a[i]))
  else
    x<-x[i,]
  }
  return(x)
}
```

**Comment by hsuknowledge** [comment]
Fixed in https://github.com/cole-trapnell-lab/monocle3/commit/fe6555d548eef7c9a808a0bbfbbfffff214564b8 .
